In [ ]:
import numpy as np

# Define the adjacency matrix representing the graph
# Example adjacency matrix for a graph with 3 states
# Replace the values based on your specific graph
graph = np.array([[0, 1, 0],
                  [0.5, 0, 0.5],
                  [1, 0, 0]])

# Compute the transition matrix
transition_matrix = graph / graph.sum(axis=1, keepdims=True)

# Compute the probabilities using matrix multiplication
probabilities = np.linalg.matrix_power(transition_matrix, 2)

# Print the probabilities
print("Probabilities of reaching one state from another state in 2 steps:")
print(probabilities)

# Calculate the stationary distribution (eigenvector corresponding to eigenvalue 1)
eigenvalues, eigenvectors = np.linalg.eig(transition_matrix.T)
stationary_distribution = np.real_if_close(
    eigenvectors[:, np.isclose(eigenvalues, 1)].T / eigenvectors[:, np.isclose(eigenvalues, 1)].sum()
)

print("Stationary Distribution (Eigenvector corresponding to Eigenvalue 1):")
print(stationary_distribution)


Probabilities of reaching one state from another state in 2 steps:
[[0.5 0.  0.5]
 [0.5 0.5 0. ]
 [0.  1.  0. ]]
Stationary Distribution (Eigenvector corresponding to Eigenvalue 1):
[[0.4 0.4 0.2]]


In [ ]:
import numpy as np

# Define the adjacency matrix representing the graph
graph = np.array([[0, 1, 0, 0],
                  [0.5, 0, 0.5, 0],
                  [0, 0.5, 0, 0.5],
                  [0, 0, 0, 1]])

# Define the indices for absorbing states (A = {0, 1, 2})
absorbing_states = [0, 1, 2]

# Define the index for the starting state B = {3}
starting_state = 3

# Extract submatrices Q and R for absorbing Markov chain computation
Q = graph[np.ix_(absorbing_states, absorbing_states)]
R = graph[np.ix_(absorbing_states, [starting_state])]

# Compute absorbing probabilities using the formula: (I - Q)^(-1) R
absorbing_probabilities = np.linalg.inv(np.eye(len(absorbing_states)) - Q) @ R

# Sum the absorbing probabilities to get the total probability of hitting A from B
probability_hitting_A_from_B = np.sum(absorbing_probabilities)

print("Probability of hitting A from B:", probability_hitting_A_from_B)



Probability of hitting A from B: 3.0


In [ ]:
import numpy as np

# Define the adjacency matrix representing the graph
graph = np.array([[0, 1, 0, 0],
                  [0.5, 0, 0.5, 0],
                  [0, 0.5, 0, 0.5],
                  [0, 0, 0, 1]])

# Define the indices for absorbing state A = {3}
absorbing_state = 3

# Define the indices for transient states B = {0, 1, 2}
transient_states = [0, 1, 2]

# Extract submatrices Q and R for absorbing Markov chain computation
Q = graph[np.ix_(transient_states, transient_states)]
R = graph[np.ix_(transient_states, [absorbing_state])]

# Compute absorbing probabilities using the formula: (I - Q)^(-1) R
absorbing_probabilities = np.linalg.inv(np.eye(len(transient_states)) - Q) @ R

# Sum the absorbing probabilities to get the total probability of hitting A = {3} from B = {0, 1, 2}
probability_hitting_A_from_B = np.sum(absorbing_probabilities)

print("Probability of hitting A = {3} from B = {0, 1, 2}:", probability_hitting_A_from_B)


Probability of hitting A = {3} from B = {0, 1, 2}: 3.0


In [ ]:
import numpy as np

# Define the adjacency matrix representing the graph
graph = np.array([[0, 1, 0, 0],
                  [0.5, 0, 0.5, 0],
                  [0, 0.5, 0, 0.5],
                  [0, 0, 0, 1]])

# Check if the Markov chain is absorbing
is_absorbing = np.all(np.diag(graph) == 1)

if is_absorbing:
    # Compute absorbing probabilities using the eigenvector method
    eigenvalues, eigenvectors = np.linalg.eig(graph.T)
    stationary_distribution = eigenvectors[:, np.isclose(eigenvalues, 1)][:, 0]
    absorbing_probabilities_eigenvector = stationary_distribution / stationary_distribution.sum()

    # Extract absorbing probabilities from the diagonal of the adjacency matrix
    absorbing_probabilities_matrix = np.diag(graph)

    # Check if the probabilities match
    probabilities_match = np.allclose(absorbing_probabilities_eigenvector, absorbing_probabilities_matrix)

    print("The Markov chain is absorbing.")
    print("Absorbing probabilities (Eigenvector Method):", absorbing_probabilities_eigenvector)
    print("Absorbing probabilities (Matrix Diagonal):", absorbing_probabilities_matrix)
    print("Do the probabilities match?", probabilities_match)
else:
    print("The Markov chain is not absorbing.")


The Markov chain is not absorbing.


In [ ]:
import numpy as np

# Define the adjacency matrix representing the graph
graph = np.array([[0, 1, 0, 0],
                  [0.5, 0, 0.5, 0],
                  [0, 0.5, 0, 0.5],
                  [0, 0, 0, 1]])

# Define the set of states A = {0, 1, 2}
A_states = [0, 1, 2]

# Initialize hitting probabilities
hitting_probabilities = np.zeros(graph.shape[0])
hitting_probabilities[A_states] = 1  # Set hitting probability to 1 for states in set A

# Perform a fixed number of iterations to ensure convergence
num_iterations = 1000

for _ in range(num_iterations):
    updated_probabilities = np.zeros_like(hitting_probabilities)
    for state in range(graph.shape[0]):
        if state not in A_states:
            updated_probabilities[state] = np.dot(graph[state], hitting_probabilities)
    hitting_probabilities = updated_probabilities

# Print hitting probabilities for states A = {0, 1, 2} from the remaining states
print("Hitting Probabilities of A = {0, 1, 2} from the remaining states:")
print(hitting_probabilities)


Hitting Probabilities of A = {0, 1, 2} from the remaining states:
[0. 0. 0. 0.]


In [ ]:
import numpy as np

# Define the adjacency matrix representing the graph
graph = np.array([[0, 1, 0, 0, 0, 0, 0],
                  [0.5, 0, 0.5, 0, 0, 0, 0],
                  [0, 0.5, 0, 0.5, 0, 0, 0],
                  [0, 0, 0.5, 0, 0.5, 0, 0],
                  [0, 0, 0, 0, 0, 1, 0],
                  [0, 0, 0, 0, 0, 1, 0],
                  [0, 0, 0, 0, 0, 0, 1]])

# Define the set of states A = {4, 5, 6}
A_states = [4, 5, 6]

# Initialize hitting probabilities
hitting_probabilities = np.zeros(graph.shape[0])
hitting_probabilities[A_states] = 1  # Set hitting probability to 1 for states in set A

# Perform a fixed number of iterations to ensure convergence
num_iterations = 1000

for _ in range(num_iterations):
    updated_probabilities = np.zeros_like(hitting_probabilities)
    for state in range(graph.shape[0]):
        if state not in A_states:
            updated_probabilities[state] = np.dot(graph[state], hitting_probabilities)
    hitting_probabilities = updated_probabilities

# Print hitting probabilities for states A = {4, 5, 6} from the remaining states
print("Hitting Probabilities of A = {4, 5, 6} from the remaining states:")
print(hitting_probabilities)


Hitting Probabilities of A = {4, 5, 6} from the remaining states:
[8.54161987e-36 0.00000000e+00 6.03983733e-36 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00]


In [ ]:
import numpy as np

# Define the adjacency matrix representing the graph
graph = np.array([[0, 1, 0, 0],
                  [0.5, 0, 0.5, 0],
                  [0, 0.5, 0, 0.5],
                  [0, 0, 0, 1]])

# Define the set of states A = {3}
A_state = 3

# Initialize hitting probabilities
hitting_probabilities = np.zeros(graph.shape[0])
hitting_probabilities[A_state] = 1  # Set hitting probability to 1 for state A

# Perform a fixed number of iterations to ensure convergence
num_iterations = 1000

for _ in range(num_iterations):
    updated_probabilities = np.zeros_like(hitting_probabilities)
    for state in range(graph.shape[0]):
        if state != A_state:
            updated_probabilities[state] = np.dot(graph[state], hitting_probabilities)
    hitting_probabilities = updated_probabilities

# Print hitting probabilities for state A = {3} from the remaining states
print("Hitting Probabilities of A = {3} from the remaining states:")
print(hitting_probabilities)


Hitting Probabilities of A = {3} from the remaining states:
[0.00000000e+00 1.13112458e-63 0.00000000e+00 0.00000000e+00]


In [ ]:
import numpy as np

# Define the adjacency matrix representing the graph
graph = np.array([[0, 1, 0, 0],
                  [0.5, 0, 0.5, 0],
                  [0, 0.5, 0, 0.5],
                  [0, 0, 0, 1]])

# Define the starting state
starting_state = 1

# Define the target state
target_state = 0

# Initialize hitting probabilities
hitting_probabilities = np.zeros(graph.shape[0])
hitting_probabilities[target_state] = 1  # Set hitting probability to 1 for the target state

# Perform iterations until convergence (all probabilities stabilize)
while True:
    updated_probabilities = np.zeros_like(hitting_probabilities)
    for state in range(graph.shape[0]):
        updated_probabilities[state] = np.dot(graph[state], hitting_probabilities)
    if np.allclose(updated_probabilities, hitting_probabilities):
        hitting_probabilities = updated_probabilities
        break
    hitting_probabilities = updated_probabilities

# Print the probability of hitting state 0 starting from state 1
print("Probability of hitting state 0 starting from state 1:", hitting_probabilities[starting_state])


Probability of hitting state 0 starting from state 1: 0.0


In [ ]:
import numpy as np

# Define the adjacency matrix representing the graph
graph = np.array([[0, 1, 0, 0, 0, 0, 0],
                  [0.5, 0, 0.5, 0, 0, 0, 0],
                  [0, 0.5, 0, 0.5, 0, 0, 0],
                  [0, 0, 0.5, 0, 0.5, 0, 0],
                  [0, 0, 0, 0, 0, 1, 0],
                  [0, 0, 0, 0, 0, 1, 0],
                  [0, 0, 0, 0, 0, 0, 1]])

# Define the starting state
starting_state = 3

# Define the target state
target_state = 6

# Initialize hitting probabilities
hitting_probabilities = np.zeros(graph.shape[0])
hitting_probabilities[target_state] = 1  # Set hitting probability to 1 for the target state

# Perform iterations until convergence (all probabilities stabilize)
while True:
    updated_probabilities = np.zeros_like(hitting_probabilities)
    for state in range(graph.shape[0]):
        updated_probabilities[state] = np.dot(graph[state], hitting_probabilities)
    if np.allclose(updated_probabilities, hitting_probabilities):
        hitting_probabilities = updated_probabilities
        break
    hitting_probabilities = updated_probabilities

# Print the probability of hitting state 6 starting from state 3
print("Probability of hitting state 6 starting from state 3:", hitting_probabilities[starting_state])


Probability of hitting state 6 starting from state 3: 0.0
