In [5]:
import numpy as np

x = np.random.rand(5) #generates a 1D NumPy array x of length 5 filled with random numbers between 0 and 1 using the np.random.rand function.

D = np.subtract.outer(x, x)  #np.subtract.outer(x, x) will be a 2D array where each element at position [i][j] represents the result of subtracting x[i] from x[j].
print(D)

[[ 0.          0.23258053  0.31034264  0.44972007  0.3738695 ]
 [-0.23258053  0.          0.07776211  0.21713955  0.14128897]
 [-0.31034264 -0.07776211  0.          0.13937744  0.06352686]
 [-0.44972007 -0.21713955 -0.13937744  0.         -0.07585058]
 [-0.3738695  -0.14128897 -0.06352686  0.07585058  0.        ]]


In [8]:
import numpy as np
x = np.random.rand(5)
D = np.array([[xi - xj for xj in x] for xi in x])
print(D)

[[ 0.         -0.04335176  0.50332562  0.11618553  0.42326909]
 [ 0.04335176  0.          0.54667738  0.15953729  0.46662084]
 [-0.50332562 -0.54667738  0.         -0.38714009 -0.08005654]
 [-0.11618553 -0.15953729  0.38714009  0.          0.30708356]
 [-0.42326909 -0.46662084  0.08005654 -0.30708356  0.        ]]
