Task 1: You have seen that the SVD of an m × n matrix A gives, among other things, a
basis for the range (column space). Compute this for the given matrix.
Another way to obtain a basis for the range is using the QR factorization, also implemented
in scipy. Carefully go through the linked QR documentation page. Then compute a basis
for the column space of a given A using QR, and then using the SVD.

In [28]:
import numpy as np
from scipy.linalg import svd, qr

In [29]:
#Given matrix A
A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])
A

array([[ 1, -2,  3, -3],
       [ 2, -4,  9, -2],
       [-3,  6, -9,  9]])

In [30]:
# Using QR Factorization
q, r = qr(A)  # The QR factorization
basis_qr = q  # Basis for the column space using QR factorization
basis_qr

array([[-0.26726124,  0.95618289, -0.11952286],
       [-0.53452248, -0.04390192,  0.84401323],
       [ 0.80178373,  0.28945968,  0.52283453]])

In [31]:
q.T

array([[-0.26726124, -0.53452248,  0.80178373],
       [ 0.95618289, -0.04390192,  0.28945968],
       [-0.11952286,  0.84401323,  0.52283453]])

In [32]:
# Using SVD
U, S, vT = svd(A)  #The SVD
basis_svd = U  # Basis for the column space using SVD
basis_svd

array([[ 2.66235859e-01,  1.70641342e-01,  9.48683298e-01],
       [ 5.39615303e-01, -8.41911709e-01, -5.55111512e-17],
       [-7.98707576e-01, -5.11924025e-01,  3.16227766e-01]])

In [33]:
U.T

array([[ 2.66235859e-01,  5.39615303e-01, -7.98707576e-01],
       [ 1.70641342e-01, -8.41911709e-01, -5.11924025e-01],
       [ 9.48683298e-01, -5.55111512e-17,  3.16227766e-01]])

In [34]:
# Verify the bases obtained from QR and SVD are the same
rank_qr = np.linalg.matrix_rank(basis_qr)
rank_svd = np.linalg.matrix_rank(basis_svd)
print("Rank_qr:",rank_qr)
print("Rank_svd:",rank_svd)

Rank_qr: 3
Rank_svd: 3


In [35]:
if rank_qr == rank_svd:
    print("The bases obtained from QR and SVD are identical.")
    print("Basis for the column space (range):")
    print(basis_qr)
else:
    print("The bases obtained from QR and SVD are different.")

The bases obtained from QR and SVD are identical.
Basis for the column space (range):
[[-0.26726124  0.95618289 -0.11952286]
 [-0.53452248 -0.04390192  0.84401323]
 [ 0.80178373  0.28945968  0.52283453]]


Task 2: Check that the column spaces (not the bases) you obtained in the two ways are the
same. (How would you check that two given bases span the same space?)

In [36]:
# Check if column spaces are the same
is_same_space = np.all(np.isclose(q @ q.T.conjugate(), U @ U.T.conjugate()))

if is_same_space:
    print("Column spaces obtained from QR factorization and SVD are the same.")
else:
    print("Column spaces obtained from QR factorization and SVD are different.")


Column spaces obtained from QR factorization and SVD are the same.


Task 3: For a 500 × 500 random matrix, which method is faster?

In [37]:
import time
# Random 500x500 matrix
random_matrix = np.random.rand(500, 500)

In [38]:
#Time taken for QR factorization
start_time_qr = time.time()
q, r = qr(random_matrix)
end_time_qr = time.time()
qr_time = end_time_qr - start_time_qr
print(f"Time taken for QR factorization: {qr_time} seconds")

Time taken for QR factorization: 0.06507706642150879 seconds


In [39]:
# Time taken for SVD
start_time_svd = time.time()
U, S, vT = svd(random_matrix)
end_time_svd = time.time()
svd_time = end_time_svd - start_time_svd
print(f"Time taken for SVD: {svd_time} seconds")

Time taken for SVD: 0.22267675399780273 seconds


In [40]:
if qr_time < svd_time:
    print("QR factorization is faster.")
elif qr_time > svd_time:
    print("SVD is faster.")
else:
    print("Both methods take the same time.")

QR factorization is faster.
