In [12]:
import numpy as np
from scipy.linalg import svd, qr

In [13]:
#Given matrix A
A = np.array([[1, -2, 9, 5, 4,], [1, -1, 6, 5, -3], [-2, 0, -6, 1, -2],[4, 1, 9, 1, -9]])
A

array([[ 1, -2,  9,  5,  4],
       [ 1, -1,  6,  5, -3],
       [-2,  0, -6,  1, -2],
       [ 4,  1,  9,  1, -9]])

Task 1: Find the null space of the given matrix A using SVD.

In [14]:
#SVD
u, s, vh = svd(A)

In [15]:
# The null space using SDV
null_space_svd = vh.T[:, np.where(s < 1e-10)].squeeze()
print("Null space using SVD:")
print(null_space_svd)

Null space using SVD:
[-0.87219483  0.3573579   0.29073161 -0.14709627 -0.07354813]


Task 2: Find the null space of the same matrix A using the QR factorization. Use the linear
algebra theorem that tells us that the null space of A is equal to the orthogonal complement
of the range of the transpose At . (How would you extract the orthogonal complement from
a full QR factorization?)

In [16]:
#QR factorization on the transpose of A
q, r = qr(A.T)

# Extract the orthogonal complement from QR factorization
null_space_qr = q[:, np.where(np.abs(np.diag(r)) < 1e-10)].squeeze()
print("Null space using QR factorization:")
print(null_space_qr)


Null space using QR factorization:
[ 0.57324869  0.68751498 -0.1910829   0.36021819  0.18010909]


Task 3: Check that both answers above span the same space.

In [17]:
# Check both null spaces span are same ya not
span_same_space = np.allclose(null_space_svd, null_space_qr)
if span_same_space:
    print("Both null spaces span the same space.")
else:
    print("Both null spaces do not span the same space.")


Both null spaces do not span the same space.
